[build]
publish = 'public'

[[headers]]
for = '*/*.txt'

  [headers.values]
  Content-Type = 'text/plain; charset=UTF-8'

[[redirects]]
from = '/'
to = 'https://osdn.net/projects/opentween/'
status = 302
force = true
